name: Build APK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
      flavor:
        description: 'Build flavor'
        required: true
        default: 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}  # Dynamically checkout the branch

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-installer@v2
        with:
          api-level: '30' # Modify as per your app requirements

      - name: Build APK
        run: ./gradlew assemble${{ github.event.inputs.flavor | capitalize }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: app/build/outputs/apk/${{ github.event.inputs.flavor }}/app-${{ github.event.inputs.flavor }}.apk